// Generates `test/.test_optimizer.dart`: a single entrypoint that imports every
// `*_test.dart` file and runs it inside a named `group()`.
//
// Why: `flutter test` compiles each test file as its own entrypoint, so a suite
// of N files pays N separate kernel compilations. Aggregating them into one
// entrypoint compiles the suite once — the trick `very_good test` uses. Run the
// generated file with `flutter test test/.test_optimizer.dart`.
//
// Usage: `dart run tool/test_optimizer.dart`
import 'dart:io';

void main() {
  final testDir = Directory('test');
  if (!testDir.existsSync()) {
    stderr.writeln('No test/ directory found.');
    exit(1);
  }

  final files =
      testDir
          .listSync(recursive: true)
          .whereType<File>()
          .map((f) => f.path)
          .where((p) => p.endsWith('_test.dart'))
          .toList()
        ..sort();

  if (files.isEmpty) {
    stderr.writeln('No *_test.dart files found under test/.');
    exit(1);
  }

  // Import URIs are relative to test/ and always use forward slashes.
  final relPaths = files
      .map(
        (p) => p.replaceFirst(RegExp(r'^test[/\\]'), '').replaceAll(r'\', '/'),
      )
      .toList();

  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/test_optimizer.dart — do not edit, do not commit.',
    )
    ..writeln(
      '// ignore_for_file: directives_ordering, avoid_relative_lib_imports',
    )
    ..writeln("import 'package:flutter_test/flutter_test.dart';");

  for (var i = 0; i < relPaths.length; i++) {
    buffer.writeln("import '${relPaths[i]}' as t$i;");
  }

  buffer
    ..writeln()
    ..writeln('void main() {');
  for (var i = 0; i < relPaths.length; i++) {
    buffer.writeln("  group('${relPaths[i]}', t$i.main);");
  }
  buffer.writeln('}');

  File('test/.test_optimizer.dart').writeAsStringSync(buffer.toString());
  stdout.writeln(
    'Wrote test/.test_optimizer.dart aggregating ${files.length} test files.',
  );
}
